import { themes, type ThemeId } from "../design-system";
import type { PanelRegistry } from "./registry";
import { WORKSPACE_FORMAT_VERSION, type DockRegion, type FloatingBounds, type PanelId, type WorkspaceLayout, type WorkspaceNode } from "./model";

const regions: readonly DockRegion[] = ["left", "right", "top", "bottom"];
function object(value: unknown, message: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(message); return value as Record<string, unknown>; }
function string(value: unknown, message: string): string { if (typeof value !== "string" || !value.trim()) throw new Error(message); return value; }
function finite(value: unknown, message: string): number { if (typeof value !== "number" || !Number.isFinite(value)) throw new Error(message); return value; }
function bounds(value: unknown): FloatingBounds { const raw = object(value, "Floating bounds are required"); const width = finite(raw.width, "Floating width must be finite"); const height = finite(raw.height, "Floating height must be finite"); if (width <= 0 || height <= 0) throw new Error("Floating dimensions must be positive"); return { x: finite(raw.x, "Floating x must be finite"), y: finite(raw.y, "Floating y must be finite"), width, height }; }

export function validateWorkspaceLayout<Factory>(value: unknown, registry?: PanelRegistry<Factory>): WorkspaceLayout {
  const raw = object(value, "Workspace layout must be an object"); if (raw.formatVersion !== WORKSPACE_FORMAT_VERSION) throw new Error(`Unsupported workspace format version: ${String(raw.formatVersion)}`); const themeId = string(raw.themeId, "Workspace theme is required") as ThemeId; if (!themes[themeId]) throw new Error(`Unknown workspace theme: ${themeId}`); const seenPanels = new Set<PanelId>(); const seenNodes = new Set<string>();
  const panel = (id: unknown): PanelId => { const result = string(id, "Panel ID must be non-empty"); if (seenPanels.has(result)) throw new Error(`Panel appears more than once: ${result}`); if (registry && !registry.has(result)) throw new Error(`Panel is not registered: ${result}`); seenPanels.add(result); return result; };
  const node = (value: unknown): WorkspaceNode => { const source = object(value, "Workspace node must be an object"); const id = string(source.id, "Workspace node ID is required"); if (seenNodes.has(id)) throw new Error(`Workspace node ID is duplicated: ${id}`); seenNodes.add(id); if (source.kind === "panel-stack") { if (!Array.isArray(source.panelIds) || !source.panelIds.length) throw new Error("Panel stack must contain panels"); const panelIds = source.panelIds.map(panel); const activePanelId = string(source.activePanelId, "Active panel ID is required"); if (!panelIds.includes(activePanelId)) throw new Error("Active panel must belong to its stack"); return { kind: "panel-stack", id, panelIds, activePanelId }; } if (source.kind === "split") { const ratio = finite(source.ratio, "Split ratio must be finite"); if (ratio <= 0 || ratio >= 1) throw new Error("Split ratio must be between 0 and 1"); if (source.axis !== "horizontal" && source.axis !== "vertical") throw new Error("Split axis is invalid"); return { kind: "split", id, axis: source.axis, ratio, first: node(source.first), second: node(source.second) }; } throw new Error(`Unsupported workspace node: ${String(source.kind)}`); };
  const rawRegions = object(raw.regions, "Workspace regions are required"); const resolvedRegions = Object.fromEntries(regions.map(region => [region, rawRegions[region] === null ? null : node(rawRegions[region])])) as Record<DockRegion, WorkspaceNode | null>; if (!Array.isArray(raw.floatingPanels)) throw new Error("Floating panels must be an array"); const floatingPanels = raw.floatingPanels.map(value => { const source = object(value, "Floating panel must be an object"); return { panelId: panel(source.panelId), bounds: bounds(source.bounds), zIndex: finite(source.zIndex, "Floating z-index must be finite") }; });
  return { formatVersion: WORKSPACE_FORMAT_VERSION, presetId: string(raw.presetId, "Workspace preset ID is required"), themeId, regions: resolvedRegions, floatingPanels };
}
export function serializeWorkspaceLayout(layout: WorkspaceLayout): string { return JSON.stringify(validateWorkspaceLayout(layout)); }
export function deserializeWorkspaceLayout<Factory>(serialized: string, registry?: PanelRegistry<Factory>): WorkspaceLayout { let parsed: unknown; try { parsed = JSON.parse(serialized); } catch (cause) { throw new Error("Workspace layout is not valid JSON", { cause }); } return validateWorkspaceLayout(parsed, registry); }
