import { describe, expect, it } from "vitest";
import { createDocument, createGroupLayer, createRasterLayer } from "../src/core";
import { createRenderInput, createRenderer, createSolidRasterSource, createViewport, InMemoryRasterSourceResolver, type CanvasCompositeSurface, type FrameScheduler, type WebGpuProbe } from "../src/renderer";

function scheduler(): { scheduler: FrameScheduler; run(): void } { let callback: (() => void) | undefined; return { scheduler: { request(next) { callback = next; return 1; }, cancel() {} }, run() { callback?.(); } }; }

describe("advanced backend compositing", () => {
  it("uses Canvas blend operations and applies isolated group opacity once", async () => {
    const frames = scheduler(); const operations: { target: string; source: string; blend: string; opacity: number }[] = [];
    const context = (target: string) => { let opacity = 1; let blend = "source-over"; return { save() {}, restore() {}, beginPath() {}, rect() {}, clip() {}, clearRect() {}, fillRect() {}, strokeRect() {}, setTransform() {}, set fillStyle(_value: string) {}, set strokeStyle(_value: string) {}, set lineWidth(_value: number) {}, set imageSmoothingEnabled(_value: boolean) {}, set globalAlpha(value: number) { opacity = value; }, set globalCompositeOperation(value: string) { blend = value; }, drawImage(source: { id?: string }) { operations.push({ target, source: source.id ?? "unknown", blend, opacity }); } } as unknown as CanvasRenderingContext2D; };
    const rootContext = context("root"); const canvas = { width: 0, height: 0, style: {}, getContext: (kind: string) => kind === "2d" ? rootContext : null } as unknown as HTMLCanvasElement; const resolver = new InMemoryRasterSourceResolver([createSolidRasterSource("child-source", 10, 10, [200, 100, 50, 180]), createSolidRasterSource("top-source", 10, 10, [20, 180, 220, 255])]); const document = createDocument("doc", "Document", 100, 100); document.layerTree.add(createGroupLayer("group", "Group", { compositing: "isolated", opacity: 0.6, blendMode: "screen" })); document.layerTree.add(createRasterLayer("child", "Child", { opacity: 0.5, blendMode: "multiply" }, { kind: "raster-reference", sourceId: "child-source", storage: "lazy" }), "group"); document.layerTree.add(createRasterLayer("top", "Top", { blendMode: "overlay" }, { kind: "raster-reference", sourceId: "top-source", storage: "lazy" }));
    const renderer = createRenderer({ scheduler: frames.scheduler, rasterSources: resolver, canvasRasterFactory: source => ({ id: source.id } as unknown as CanvasImageSource), canvasCompositeSurfaceFactory: (width, height) => { const surface = { id: "group-surface", width, height, getContext: () => context("offscreen") }; return surface as unknown as CanvasCompositeSurface; } }); renderer.attach(canvas); renderer.resize(createViewport(100, 100)); await renderer.initialize(); await renderer.render(createRenderInput(document)); frames.run();
    expect(operations).toEqual([{ target: "offscreen", source: "child-source", blend: "multiply", opacity: 0.5 }, { target: "root", source: "group-surface", blend: "screen", opacity: 0.6 }, { target: "root", source: "top-source", blend: "overlay", opacity: 1 }]); renderer.dispose();
  });

  it("uses distinct WebGPU ping-pong targets for destination-sampled isolated composition", async () => {
    const frames = scheduler(); let textureId = 0; const usages: number[] = []; const copies: [number, number][] = []; const shaderCodes: string[] = []; const bindEntries: number[][] = []; const pipelines: unknown[] = []; const canvas = { width: 0, height: 0, style: {}, getContext: () => ({ configure() {}, getCurrentTexture: () => ({ createView: () => ({ surface: true }) }) }) } as unknown as HTMLCanvasElement;
    const webGpu: WebGpuProbe = { getPreferredCanvasFormat: () => "rgba8unorm", requestAdapter: async () => ({ requestDevice: async () => ({ queue: { submit() {}, writeBuffer() {}, writeTexture() {} }, createShaderModule: descriptor => { shaderCodes.push(descriptor.code); return {}; }, createBindGroupLayout: () => ({}), createPipelineLayout: () => ({}), createRenderPipeline: descriptor => { pipelines.push(descriptor); return {}; }, createBuffer: () => ({ destroy() {} }), createBindGroup: descriptor => { bindEntries.push((descriptor as { entries: { binding: number }[] }).entries.map(entry => entry.binding)); return {}; }, createSampler: () => ({}), createTexture: (descriptor: unknown) => { const typed = descriptor as { usage: number }; usages.push(typed.usage); const id = ++textureId; return { createView: () => ({ id }), destroy() {}, id } as never; }, createCommandEncoder: () => ({ copyTextureToTexture(source, destination) { const from = (source.texture as unknown as { id: number }).id; const to = (destination.texture as unknown as { id: number }).id; copies.push([from, to]); }, beginRenderPass: () => ({ setPipeline() {}, setBindGroup() {}, draw() {}, end() {} }), finish: () => ({}) }) }) }) };
    const resolver = new InMemoryRasterSourceResolver([createSolidRasterSource("source", 10, 10, [255, 128, 64, 160])]); const document = createDocument("doc", "Document", 100, 100); document.layerTree.add(createGroupLayer("group", "Group", { compositing: "isolated", opacity: 0.7, blendMode: "screen" })); document.layerTree.add(createRasterLayer("layer", "Layer", { blendMode: "multiply" }, { kind: "raster-reference", sourceId: "source", storage: "lazy" }), "group"); const renderer = createRenderer({ webGpu, scheduler: frames.scheduler, rasterSources: resolver }); renderer.attach(canvas); renderer.resize(createViewport(100, 100)); await renderer.initialize(); await renderer.render(createRenderInput(document)); frames.run();
    expect(renderer.status).toBe("ready"); expect(copies).toHaveLength(3); expect(copies.every(([source, destination]) => source !== destination)).toBe(true); expect(usages.filter(usage => usage === 23)).toHaveLength(4); expect(shaderCodes.some(code => code.includes("destinationTexture"))).toBe(true); expect(bindEntries.some(bindings => bindings.join(",") === "0,1,2,3")).toBe(true); expect((pipelines[0] as { fragment: { targets: { blend?: unknown }[] } }).fragment.targets[0].blend).toBeUndefined(); renderer.dispose();
  });
});
