import type { ButtonHTMLAttributes, HTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes } from "react";
import { Icon, type IconName } from "./icons";

export function Button({ appearance = "default", selected, className = "", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { readonly appearance?: "default" | "primary" | "subtle"; readonly selected?: boolean }) { return <button className={`ui-button ui-button--${appearance} ${className}`} aria-pressed={selected} {...props} />; }
export function IconButton({ label, icon, selected, ...props }: Omit<ButtonHTMLAttributes<HTMLButtonElement>, "children" | "aria-label"> & { readonly label: string; readonly icon: IconName; readonly selected?: boolean }) { return <button type="button" className="ui-icon-button" aria-label={label} aria-pressed={selected} title={label} {...props}><Icon name={icon} /></button>; }
export function Surface({ level = "panel", className = "", ...props }: HTMLAttributes<HTMLDivElement> & { readonly level?: "panel" | "floating" | "toolbar" | "overlay" }) { return <div className={`ui-surface ui-surface--${level} ${className}`} {...props} />; }
export function Divider() { return <span className="ui-divider" role="separator" />; }
export function TextInput({ label, id, ...props }: InputHTMLAttributes<HTMLInputElement> & { readonly label: string; readonly id: string }) { return <label className="ui-field" htmlFor={id}><span>{label}</span><input id={id} {...props} /></label>; }
export function Select({ label, id, children, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { readonly label: string; readonly id: string; readonly children: ReactNode }) { return <label className="ui-field" htmlFor={id}><span>{label}</span><select id={id} {...props}>{children}</select></label>; }
export function PanelChrome({ title, icon, actions, children }: { readonly title: string; readonly icon: IconName; readonly actions?: ReactNode; readonly children: ReactNode }) { return <section className="panel-chrome" aria-label={title}><header className="panel-chrome__header"><Icon name={icon} /><h2>{title}</h2><div className="panel-chrome__actions">{actions}</div></header><div className="panel-chrome__content">{children}</div></section>; }
export function ScrollArea({ className = "", ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={`ui-scroll-area ${className}`} tabIndex={0} {...props} />; }
