import type { BlendMode } from "../core";
import { BLEND_MODE_INDEX, canvasCompositeOperation } from "./compositing";
import type { RenderBackendKind, RenderInput, RenderLayerTransformPreview, RenderOptions, Renderer, RendererError, RendererIssue, RendererStatus, RendererStatusDetail, RenderViewport } from "./contracts";
import { OffscreenSurfacePool, type OffscreenSurfaceDescriptor } from "./offscreen";
import { createSolidRasterSource, InMemoryRasterSourceResolver, prepareTextureUpload, RasterResourceCache, type RasterSource, type RasterSourceResolver } from "./raster-source";
import { calculateRenderNodeBounds, createRenderPlan, previewAffectsNode, previewedNodeTransform, type RenderBounds, type RenderPlan, type RenderPlanNode, type RenderPlanRaster } from "./render-plan";
import { multiplyAffine, transformPoint, type AffineTransform } from "./transform";
import { actualSize, clampZoom, fitDocument, fitWidth, inputSize, panBy, panTo, physicalSurfaceSize, withZoom, zoomAround } from "./viewport";

export type TextureSampling = "nearest" | "linear";
export interface WebGpuTexture { createView(): unknown; destroy?(): void; }
export interface WebGpuBuffer { destroy?(): void; }
export interface WebGpuRenderPass { setPipeline(pipeline: unknown): void; setBindGroup(index: number, group: unknown): void; draw(vertices: number): void; end(): void; }
export interface WebGpuCommandEncoder { beginRenderPass(descriptor: unknown): WebGpuRenderPass; copyTextureToTexture(source: { texture: WebGpuTexture }, destination: { texture: WebGpuTexture }, size: { width: number; height: number; depthOrArrayLayers: number }): void; finish(): unknown; }
export interface WebGpuDevice {
  readonly queue?: { submit(commands: unknown[]): void; writeBuffer?(buffer: unknown, offset: number, data: ArrayBufferView): void; writeTexture?(destination: { texture: WebGpuTexture }, data: ArrayBufferView, layout: { bytesPerRow: number; rowsPerImage: number }, size: { width: number; height: number; depthOrArrayLayers: number }): void };
  createCommandEncoder?(): WebGpuCommandEncoder; createShaderModule?(descriptor: { code: string }): unknown; createBindGroupLayout?(descriptor: unknown): unknown; createPipelineLayout?(descriptor: unknown): unknown; createRenderPipeline?(descriptor: unknown): unknown; createBuffer?(descriptor: unknown): WebGpuBuffer; createBindGroup?(descriptor: unknown): unknown; createTexture?(descriptor: unknown): WebGpuTexture; createSampler?(descriptor: unknown): unknown;
}
export interface WebGpuAdapter { readonly name?: string; requestDevice?(): Promise<WebGpuDevice>; }
export interface WebGpuProbe { requestAdapter(): Promise<WebGpuAdapter | null>; getPreferredCanvasFormat?(): string; }
export interface FrameScheduler { request(callback: () => void): number; cancel(handle: number): void; }
export type CanvasRasterFactory = (source: RasterSource) => CanvasImageSource;
export interface CanvasCompositeSurface { width: number; height: number; getContext(kind: "2d"): CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D | null; }
export type CanvasCompositeSurfaceFactory = (width: number, height: number) => CanvasCompositeSurface;
export interface RendererDependencies { readonly webGpu?: WebGpuProbe; readonly scheduler?: FrameScheduler; readonly rasterSources?: RasterSourceResolver; readonly sampling?: TextureSampling; readonly canvasRasterFactory?: CanvasRasterFactory; readonly canvasCompositeSurfaceFactory?: CanvasCompositeSurfaceFactory; }

interface RenderBackend { readonly kind: RenderBackendKind; readonly issues: readonly RendererIssue[]; initialize(surface: HTMLCanvasElement, viewport: RenderViewport): Promise<void>; resize(viewport: RenderViewport): void; render(input: RenderInput | undefined, plan: RenderPlan | undefined, viewport: RenderViewport, options: RenderOptions | undefined, refreshResources: boolean, preview: RenderLayerTransformPreview | undefined): void; invalidateRaster(sourceId: string): void; dispose(): void; }
interface WebGpuCanvasContext { configure(config: { device: WebGpuDevice; format: string; alphaMode: "opaque" }): void; getCurrentTexture(): { createView(): unknown }; }
interface CanvasRasterResource { readonly width: number; readonly height: number; readonly drawable: CanvasImageSource; }
type CanvasContext = CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D;
interface CanvasSurfaceResource { readonly surface: CanvasCompositeSurface; readonly context: CanvasContext; }
interface CanvasTarget { readonly context: CanvasContext; readonly originX: number; readonly originY: number; }
interface GpuTextureResource { readonly key: string; readonly width: number; readonly height: number; readonly texture: WebGpuTexture; readonly view: unknown; }
interface GpuDrawResource { readonly uniform: WebGpuBuffer; readonly data: Float32Array; readonly groups: Map<string, unknown>; }
interface GpuCompositeTarget { readonly key: string; readonly width: number; readonly height: number; originX: number; originY: number; readonly textures: readonly [GpuTextureResource, GpuTextureResource]; current: 0 | 1; }
interface PixelBounds { readonly x: number; readonly y: number; readonly width: number; readonly height: number; }

const defaultScheduler: FrameScheduler = { request: callback => typeof requestAnimationFrame === "function" ? requestAnimationFrame(callback) : setTimeout(callback, 0) as unknown as number, cancel: handle => typeof cancelAnimationFrame === "function" ? cancelAnimationFrame(handle) : clearTimeout(handle) };
const noRasterSources = new InMemoryRasterSourceResolver();
function viewportAffine(viewport: RenderViewport): AffineTransform { return { a: viewport.zoom * viewport.devicePixelRatio, b: 0, c: 0, d: viewport.zoom * viewport.devicePixelRatio, e: viewport.offsetX * viewport.devicePixelRatio, f: viewport.offsetY * viewport.devicePixelRatio }; }
function offsetAffine(transform: AffineTransform, originX: number, originY: number): AffineTransform { return { ...transform, e: transform.e - originX, f: transform.f - originY }; }
function projectBounds(bounds: RenderBounds, view: AffineTransform, surface: { width: number; height: number }): PixelBounds | undefined { if (![bounds.x, bounds.y, bounds.width, bounds.height, view.a, view.b, view.c, view.d, view.e, view.f, surface.width, surface.height].every(Number.isFinite) || bounds.width < 0 || bounds.height < 0 || surface.width <= 0 || surface.height <= 0) return undefined; const points = [transformPoint(view, { x: bounds.x, y: bounds.y }), transformPoint(view, { x: bounds.x + bounds.width, y: bounds.y }), transformPoint(view, { x: bounds.x, y: bounds.y + bounds.height }), transformPoint(view, { x: bounds.x + bounds.width, y: bounds.y + bounds.height })]; if (!points.every(point => Number.isFinite(point.x) && Number.isFinite(point.y))) return undefined; const left = Math.max(0, Math.floor(Math.min(...points.map(point => point.x)))); const top = Math.max(0, Math.floor(Math.min(...points.map(point => point.y)))); const right = Math.min(surface.width, Math.ceil(Math.max(...points.map(point => point.x)))); const bottom = Math.min(surface.height, Math.ceil(Math.max(...points.map(point => point.y)))); return right > left && bottom > top ? { x: left, y: top, width: right - left, height: bottom - top } : undefined; }
function defaultCanvasRasterFactory(source: RasterSource): CanvasImageSource { const surface = typeof OffscreenCanvas === "function" ? new OffscreenCanvas(source.width, source.height) : document.createElement("canvas"); surface.width = source.width; surface.height = source.height; const context = surface.getContext("2d") as CanvasContext | null; if (!context) throw new Error("Canvas raster resource context is unavailable"); const image = context.createImageData(source.width, source.height); image.data.set(source.pixels); context.putImageData(image, 0, 0); return surface as CanvasImageSource; }
function defaultCanvasCompositeSurfaceFactory(width: number, height: number): CanvasCompositeSurface { const surface = typeof OffscreenCanvas === "function" ? new OffscreenCanvas(width, height) : document.createElement("canvas"); surface.width = width; surface.height = height; return surface as CanvasCompositeSurface; }

class Canvas2dBackend implements RenderBackend {
  readonly kind = "canvas2d" as const; #context?: CanvasRenderingContext2D; #resources: RasterResourceCache<CanvasRasterResource>; #surfaces: OffscreenSurfacePool<CanvasSurfaceResource>; #issues: RendererIssue[] = [];
  constructor(resolver: RasterSourceResolver, factory: CanvasRasterFactory, surfaceFactory: CanvasCompositeSurfaceFactory, private readonly sampling: TextureSampling) { this.#resources = new RasterResourceCache(resolver, source => ({ width: source.width, height: source.height, drawable: factory(source) })); this.#surfaces = new OffscreenSurfacePool(descriptor => { const surface = surfaceFactory(descriptor.width, descriptor.height); const context = surface.getContext("2d"); if (!context) throw new Error("Canvas offscreen context is unavailable"); return { surface, context }; }); }
  async initialize(surface: HTMLCanvasElement, _viewport: RenderViewport): Promise<void> { const context = surface.getContext("2d"); if (!context) throw new Error("Canvas 2D context is unavailable"); this.#context = context; }
  get issues(): readonly RendererIssue[] { return this.#issues; }
  resize(_viewport: RenderViewport): void {}
  render(input: RenderInput | undefined, plan: RenderPlan | undefined, viewport: RenderViewport, _options: RenderOptions | undefined, refreshResources: boolean, preview: RenderLayerTransformPreview | undefined): void {
    if (!this.#context) throw new Error("Canvas backend is not initialized"); const context = this.#context; const physical = physicalSurfaceSize(viewport); context.save(); context.setTransform(1, 0, 0, 1, 0, 0); context.globalAlpha = 1; context.globalCompositeOperation = "source-over"; context.fillStyle = "#1b1f2a"; context.fillRect(0, 0, physical.width, physical.height); context.restore(); this.#issues = []; this.#resources.beginUsage(); this.#surfaces.beginUsage();
    try { if (input && plan) { const view = viewportAffine(viewport); context.save(); context.beginPath(); context.rect(0, 0, physical.width, physical.height); context.clip(); context.setTransform(view.a, view.b, view.c, view.d, view.e, view.f); context.globalAlpha = 1; context.globalCompositeOperation = "source-over"; context.fillStyle = "#f2f3f5"; context.fillRect(0, 0, input.width, input.height); context.strokeStyle = "#9aa0a8"; context.lineWidth = 1 / Math.max(viewport.zoom * viewport.devicePixelRatio, Number.EPSILON); context.strokeRect(0, 0, input.width, input.height); context.restore(); this.#drawNodes(plan.nodes, { context, originX: 0, originY: 0 }, view, physical, refreshResources, preview); } } finally { this.#surfaces.endUsage(); this.#resources.endUsage(); }
  }
  #drawNodes(nodes: readonly RenderPlanNode[], target: CanvasTarget, view: AffineTransform, physical: { width: number; height: number }, refreshResources: boolean, preview: RenderLayerTransformPreview | undefined, inheritedPreview = false): void {
    for (const node of nodes) { const affectsPreview = previewAffectsNode(node, preview, inheritedPreview); if (node.kind === "raster") { const bounds = this.#bounds(node, refreshResources, preview, inheritedPreview); if (!bounds || !projectBounds(bounds, view, physical)) continue; const resource = refreshResources ? this.#resources.get(node.raster) : this.#resources.getCached(node.raster); if (!resource) { this.#recordIssue(node.layerId); continue; } const transform = offsetAffine(multiplyAffine(view, previewedNodeTransform(node, preview, inheritedPreview)), target.originX, target.originY); const context = target.context; context.save(); context.setTransform(transform.a, transform.b, transform.c, transform.d, transform.e, transform.f); context.globalAlpha = node.opacity; context.globalCompositeOperation = canvasCompositeOperation(node.blendMode); context.imageSmoothingEnabled = this.sampling === "linear"; context.drawImage(resource.drawable, 0, 0, resource.width, resource.height); context.restore(); continue; }
      if (node.mode === "pass-through") { this.#drawNodes(node.children, target, view, physical, refreshResources, preview, affectsPreview); continue; } const bounds = calculateRenderNodeBounds(node, layer => this.#bounds(layer, refreshResources), preview, inheritedPreview); const pixels = bounds && projectBounds(bounds, view, physical); if (!pixels) continue; const offscreen = this.#surfaces.acquire({ key: node.layerId, width: pixels.width, height: pixels.height }); offscreen.context.save(); offscreen.context.setTransform(1, 0, 0, 1, 0, 0); offscreen.context.clearRect(0, 0, pixels.width, pixels.height); offscreen.context.restore(); this.#drawNodes(node.children, { context: offscreen.context, originX: pixels.x, originY: pixels.y }, view, physical, refreshResources, preview, affectsPreview); const context = target.context; context.save(); context.setTransform(1, 0, 0, 1, pixels.x - target.originX, pixels.y - target.originY); context.globalAlpha = node.opacity; context.globalCompositeOperation = canvasCompositeOperation(node.blendMode); context.imageSmoothingEnabled = this.sampling === "linear"; context.drawImage(offscreen.surface as CanvasImageSource, 0, 0); context.restore(); }
  }
  #bounds(layer: RenderPlanRaster, refreshResources: boolean, preview?: RenderLayerTransformPreview, inheritedPreview = false): RenderBounds | undefined { const size = this.#resources.getDimensions(layer.raster, refreshResources); if (!size) { this.#recordIssue(layer.layerId); return undefined; } return calculateRenderNodeBounds(layer, () => size, preview, inheritedPreview); }
  invalidateRaster(sourceId: string): void { this.#resources.invalidate(sourceId); }
  #recordIssue(layerId: string): void { const error = this.#resources.lastError; if (error && !this.#issues.some(issue => issue.layerId === layerId && issue.code === error.code)) this.#issues.push({ code: error.code, message: error.message, sourceId: error.sourceId, cause: error.cause, layerId }); }
  dispose(): void { this.#context = undefined; this.#resources.dispose(); this.#surfaces.dispose(); }
}

class WebGpuBackend implements RenderBackend {
  readonly kind = "webgpu" as const; #device?: WebGpuDevice; #context?: WebGpuCanvasContext; #format?: string; #pipeline?: unknown; #layout?: unknown; #presentPipeline?: unknown; #presentLayout?: unknown; #sampler?: unknown; #board?: GpuTextureResource; #drawResources: GpuDrawResource[] = []; #presentGroups = new Map<string, unknown>(); #resources: RasterResourceCache<GpuTextureResource>; #targets: OffscreenSurfacePool<GpuCompositeTarget>; #issues: RendererIssue[] = []; #drawIndex = 0;
  constructor(private readonly probe: WebGpuProbe, resolver: RasterSourceResolver, private readonly sampling: TextureSampling) { this.#resources = new RasterResourceCache(resolver, source => this.#uploadTexture(source), resource => this.#disposeRasterResource(resource)); this.#targets = new OffscreenSurfacePool(descriptor => this.#createTarget(descriptor), target => this.#destroyTarget(target)); }
  get issues(): readonly RendererIssue[] { return this.#issues; }
  async initialize(surface: HTMLCanvasElement, _viewport: RenderViewport): Promise<void> {
    const adapter = await this.probe.requestAdapter(); if (!adapter?.requestDevice) throw new Error("WebGPU adapter or device is unavailable"); const context = surface.getContext("webgpu") as unknown as WebGpuCanvasContext | null; if (!context) throw new Error("WebGPU canvas context is unavailable"); this.#device = await adapter.requestDevice(); this.#context = context; this.#format = this.probe.getPreferredCanvasFormat?.() ?? "bgra8unorm"; const device = this.#device;
    if (!device.queue?.writeTexture || !device.createShaderModule || !device.createBindGroupLayout || !device.createPipelineLayout || !device.createRenderPipeline || !device.createBuffer || !device.createBindGroup || !device.createTexture || !device.createSampler || !device.createCommandEncoder) throw new Error("WebGPU compositing resources are unavailable");
    const module = device.createShaderModule({ code: COMPOSITE_SHADER }); const layout = device.createBindGroupLayout({ entries: [{ binding: 0, visibility: 3, buffer: { type: "uniform" } }, { binding: 1, visibility: 2, texture: { sampleType: "float", viewDimension: "2d" } }, { binding: 2, visibility: 2, sampler: { type: "filtering" } }, { binding: 3, visibility: 2, texture: { sampleType: "float", viewDimension: "2d" } }] }); this.#layout = layout; this.#sampler = device.createSampler({ addressModeU: "clamp-to-edge", addressModeV: "clamp-to-edge", magFilter: this.sampling, minFilter: this.sampling }); this.#pipeline = device.createRenderPipeline({ layout: device.createPipelineLayout({ bindGroupLayouts: [layout] }), vertex: { module, entryPoint: "vertexMain" }, fragment: { module, entryPoint: "fragmentMain", targets: [{ format: this.#format }] }, primitive: { topology: "triangle-list" } });
    const presentModule = device.createShaderModule({ code: PRESENT_SHADER }); const presentLayout = device.createBindGroupLayout({ entries: [{ binding: 0, visibility: 2, texture: { sampleType: "float", viewDimension: "2d" } }, { binding: 1, visibility: 2, sampler: { type: "filtering" } }] }); this.#presentLayout = presentLayout; this.#presentPipeline = device.createRenderPipeline({ layout: device.createPipelineLayout({ bindGroupLayouts: [presentLayout] }), vertex: { module: presentModule, entryPoint: "vertexMain" }, fragment: { module: presentModule, entryPoint: "fragmentMain", targets: [{ format: this.#format }] }, primitive: { topology: "triangle-list" } }); this.#board = this.#uploadTexture(createSolidRasterSource("renderer-board", 1, 1, [242, 243, 245, 255])); context.configure({ device, format: this.#format, alphaMode: "opaque" });
  }
  resize(_viewport: RenderViewport): void { if (this.#context && this.#device && this.#format) this.#context.configure({ device: this.#device, format: this.#format, alphaMode: "opaque" }); }
  render(input: RenderInput | undefined, plan: RenderPlan | undefined, viewport: RenderViewport, _options: RenderOptions | undefined, refreshResources: boolean, preview: RenderLayerTransformPreview | undefined): void {
    if (!this.#device?.createCommandEncoder || !this.#device.queue || !this.#context || !this.#pipeline || !this.#layout || !this.#presentPipeline || !this.#presentLayout || !this.#sampler || !this.#board) throw new Error("WebGPU backend is not initialized"); const encoder = this.#device.createCommandEncoder(); if (typeof encoder.copyTextureToTexture !== "function") throw new Error("WebGPU texture copy support is unavailable"); this.#issues = []; this.#drawIndex = 0; this.#resources.beginUsage(); this.#targets.beginUsage();
    try { if (input && plan) { const physical = physicalSurfaceSize(viewport); const view = viewportAffine(viewport); const root = this.#targets.acquire({ key: "renderer-root", width: physical.width, height: physical.height }); root.originX = 0; root.originY = 0; this.#clearTarget(encoder, root, { r: 0.106, g: 0.122, b: 0.165, a: 1 }); this.#compositeTexture(encoder, root, this.#board, view, input.width, input.height, 1, "normal"); this.#drawNodes(encoder, plan.nodes, root, view, physical, refreshResources, preview); this.#present(encoder, root); } else { const pass = encoder.beginRenderPass({ colorAttachments: [{ view: this.#context.getCurrentTexture().createView(), clearValue: { r: 0.106, g: 0.122, b: 0.165, a: 1 }, loadOp: "clear", storeOp: "store" }] }); pass.end(); } this.#device.queue.submit([encoder.finish()]); } finally { this.#targets.endUsage(); this.#resources.endUsage(); }
  }
  #drawNodes(encoder: WebGpuCommandEncoder, nodes: readonly RenderPlanNode[], target: GpuCompositeTarget, view: AffineTransform, physical: { width: number; height: number }, refreshResources: boolean, preview: RenderLayerTransformPreview | undefined, inheritedPreview = false): void {
    for (const node of nodes) { const affectsPreview = previewAffectsNode(node, preview, inheritedPreview); if (node.kind === "raster") { const bounds = this.#bounds(node, refreshResources, preview, inheritedPreview); if (!bounds || !projectBounds(bounds, view, physical)) continue; const resource = refreshResources ? this.#resources.get(node.raster) : this.#resources.getCached(node.raster); if (!resource) { this.#recordIssue(node.layerId); continue; } this.#compositeTexture(encoder, target, resource, offsetAffine(multiplyAffine(view, previewedNodeTransform(node, preview, inheritedPreview)), target.originX, target.originY), resource.width, resource.height, node.opacity, node.blendMode); continue; } if (node.mode === "pass-through") { this.#drawNodes(encoder, node.children, target, view, physical, refreshResources, preview, affectsPreview); continue; } const bounds = calculateRenderNodeBounds(node, layer => this.#bounds(layer, refreshResources), preview, inheritedPreview); const pixels = bounds && projectBounds(bounds, view, physical); if (!pixels) continue; const group = this.#targets.acquire({ key: `group:${node.layerId}`, width: pixels.width, height: pixels.height }); group.originX = pixels.x; group.originY = pixels.y; this.#clearTarget(encoder, group, { r: 0, g: 0, b: 0, a: 0 }); this.#drawNodes(encoder, node.children, group, view, physical, refreshResources, preview, affectsPreview); const source = group.textures[group.current]; this.#compositeTexture(encoder, target, { ...source, key: `${group.key}:${group.current}` }, { a: 1, b: 0, c: 0, d: 1, e: group.originX - target.originX, f: group.originY - target.originY }, group.width, group.height, node.opacity, node.blendMode); }
  }
  #bounds(layer: RenderPlanRaster, refreshResources: boolean, preview?: RenderLayerTransformPreview, inheritedPreview = false): RenderBounds | undefined { const size = this.#resources.getDimensions(layer.raster, refreshResources); if (!size) { this.#recordIssue(layer.layerId); return undefined; } return calculateRenderNodeBounds(layer, () => size, preview, inheritedPreview); }
  #createTarget(descriptor: OffscreenSurfaceDescriptor): GpuCompositeTarget { const first = this.#createRenderTexture(`${descriptor.key}:0`, descriptor.width, descriptor.height); const second = this.#createRenderTexture(`${descriptor.key}:1`, descriptor.width, descriptor.height); return { key: descriptor.key, width: descriptor.width, height: descriptor.height, originX: 0, originY: 0, textures: [first, second], current: 0 }; }
  #destroyTarget(target: GpuCompositeTarget): void { target.textures.forEach(resource => resource.texture.destroy?.()); this.#drawResources.forEach(draw => { [...draw.groups.keys()].filter(key => key.includes(target.key)).forEach(key => draw.groups.delete(key)); }); [...this.#presentGroups.keys()].filter(key => key.startsWith(`${target.key}:`)).forEach(key => this.#presentGroups.delete(key)); }
  #createRenderTexture(key: string, width: number, height: number): GpuTextureResource { const texture = this.#device!.createTexture!({ size: { width, height, depthOrArrayLayers: 1 }, format: this.#format, usage: 23 }); return { key, width, height, texture, view: texture.createView() }; }
  #clearTarget(encoder: WebGpuCommandEncoder, target: GpuCompositeTarget, color: { r: number; g: number; b: number; a: number }): void { target.current = 0; const pass = encoder.beginRenderPass({ colorAttachments: [{ view: target.textures[0].view, clearValue: color, loadOp: "clear", storeOp: "store" }] }); pass.end(); }
  #compositeTexture(encoder: WebGpuCommandEncoder, target: GpuCompositeTarget, source: GpuTextureResource, transform: AffineTransform, width: number, height: number, opacity: number, mode: BlendMode): void {
    const previous = target.current; const next = previous === 0 ? 1 : 0; encoder.copyTextureToTexture({ texture: target.textures[previous].texture }, { texture: target.textures[next].texture }, { width: target.width, height: target.height, depthOrArrayLayers: 1 }); const pass = encoder.beginRenderPass({ colorAttachments: [{ view: target.textures[next].view, loadOp: "load", storeOp: "store" }] }); const draw = this.#drawResource(this.#drawIndex++); const key = `${source.key}|${target.key}:${previous}`; let group = draw.groups.get(key); if (!group) { group = this.#device!.createBindGroup!({ layout: this.#layout, entries: [{ binding: 0, resource: { buffer: draw.uniform } }, { binding: 1, resource: source.view }, { binding: 2, resource: this.#sampler }, { binding: 3, resource: target.textures[previous].view }] }); draw.groups.set(key, group); } const data = draw.data; data[0] = transform.a; data[1] = transform.b; data[2] = transform.c; data[3] = transform.d; data[4] = transform.e; data[5] = transform.f; data[6] = width; data[7] = height; data[8] = opacity; data[9] = BLEND_MODE_INDEX[mode]; data[10] = target.width; data[11] = target.height; this.#device!.queue!.writeBuffer?.(draw.uniform, 0, data); pass.setPipeline(this.#pipeline!); pass.setBindGroup(0, group); pass.draw(6); pass.end(); target.current = next;
  }
  #drawResource(index: number): GpuDrawResource { while (this.#drawResources.length <= index) this.#drawResources.push({ uniform: this.#device!.createBuffer!({ size: 48, usage: 72 }), data: new Float32Array(12), groups: new Map() }); return this.#drawResources[index]; }
  /** Bind groups retain texture views, so cache eviction must retire every group that references the evicted texture. */
  #disposeRasterResource(resource: GpuTextureResource): void { resource.texture.destroy?.(); const prefix = `${resource.key}|`; this.#drawResources.forEach(draw => { [...draw.groups.keys()].filter(key => key.startsWith(prefix)).forEach(key => draw.groups.delete(key)); }); }
  #present(encoder: WebGpuCommandEncoder, target: GpuCompositeTarget): void { const source = target.textures[target.current]; const key = `${target.key}:${target.current}`; let group = this.#presentGroups.get(key); if (!group) { group = this.#device!.createBindGroup!({ layout: this.#presentLayout, entries: [{ binding: 0, resource: source.view }, { binding: 1, resource: this.#sampler }] }); this.#presentGroups.set(key, group); } const pass = encoder.beginRenderPass({ colorAttachments: [{ view: this.#context!.getCurrentTexture().createView(), clearValue: { r: 0, g: 0, b: 0, a: 1 }, loadOp: "clear", storeOp: "store" }] }); pass.setPipeline(this.#presentPipeline!); pass.setBindGroup(0, group); pass.draw(6); pass.end(); }
  #uploadTexture(source: RasterSource): GpuTextureResource { const upload = prepareTextureUpload(source); const texture = this.#device!.createTexture!({ size: { width: source.width, height: source.height, depthOrArrayLayers: 1 }, format: "rgba8unorm", usage: 6 }); try { this.#device!.queue!.writeTexture!({ texture }, upload.data, { bytesPerRow: upload.layout.bytesPerRow, rowsPerImage: upload.layout.rowsPerImage }, { width: source.width, height: source.height, depthOrArrayLayers: 1 }); return { key: `${source.id}:${source.revision}`, width: source.width, height: source.height, texture, view: texture.createView() }; } catch (error) { texture.destroy?.(); throw error; } }
  invalidateRaster(sourceId: string): void { this.#resources.invalidate(sourceId); }
  #recordIssue(layerId: string): void { const error = this.#resources.lastError; if (error && !this.#issues.some(issue => issue.layerId === layerId && issue.code === error.code)) this.#issues.push({ code: error.code, message: error.message, sourceId: error.sourceId, cause: error.cause, layerId }); }
  dispose(): void { this.#resources.dispose(); this.#targets.dispose(); this.#board?.texture.destroy?.(); this.#board = undefined; this.#drawResources.forEach(draw => draw.uniform.destroy?.()); this.#drawResources = []; this.#presentGroups.clear(); this.#context = undefined; this.#device = undefined; this.#format = undefined; this.#pipeline = undefined; this.#layout = undefined; this.#presentPipeline = undefined; this.#presentLayout = undefined; this.#sampler = undefined; }
}

const COMPOSITE_SHADER = `struct Quad { linear: vec4f, translation: vec4f, params: vec4f }
struct VertexOutput { @builtin(position) position: vec4f, @location(0) uv: vec2f }
@group(0) @binding(0) var<uniform> quad: Quad;
@group(0) @binding(1) var sourceTexture: texture_2d<f32>;
@group(0) @binding(2) var sourceSampler: sampler;
@group(0) @binding(3) var destinationTexture: texture_2d<f32>;
@vertex fn vertexMain(@builtin(vertex_index) index: u32) -> VertexOutput {
  let points = array<vec2f, 6>(vec2f(0.0, 0.0), vec2f(1.0, 0.0), vec2f(0.0, 1.0), vec2f(0.0, 1.0), vec2f(1.0, 0.0), vec2f(1.0, 1.0)); let uv = points[index]; let source = uv * quad.translation.zw; let point = vec2f(quad.linear.x * source.x + quad.linear.z * source.y + quad.translation.x, quad.linear.y * source.x + quad.linear.w * source.y + quad.translation.y); var output: VertexOutput; output.position = vec4f(point.x / quad.params.z * 2.0 - 1.0, 1.0 - point.y / quad.params.w * 2.0, 0.0, 1.0); output.uv = uv; return output;
}
fn straight(color: vec4f) -> vec3f { if (color.a <= 0.0) { return vec3f(0.0); } return color.rgb / color.a; }
fn blend(backdrop: vec3f, source: vec3f, mode: u32) -> vec3f { if (mode == 1u) { return backdrop * source; } if (mode == 2u) { return backdrop + source - backdrop * source; } if (mode == 3u) { return select(2.0 * backdrop * source, 1.0 - 2.0 * (1.0 - backdrop) * (1.0 - source), backdrop > vec3f(0.5)); } return source; }
@fragment fn fragmentMain(input: VertexOutput) -> @location(0) vec4f { let source = textureSample(sourceTexture, sourceSampler, input.uv) * quad.params.x; let destination = textureLoad(destinationTexture, vec2i(input.position.xy), 0); let mixed = blend(straight(destination), straight(source), u32(quad.params.y)); let overlap = source.a * destination.a; let rgb = source.rgb * (1.0 - destination.a) + mixed * overlap + destination.rgb * (1.0 - source.a); return vec4f(rgb, source.a + destination.a * (1.0 - source.a)); }`;
const PRESENT_SHADER = `struct VertexOutput { @builtin(position) position: vec4f, @location(0) uv: vec2f }
@group(0) @binding(0) var sourceTexture: texture_2d<f32>;
@group(0) @binding(1) var sourceSampler: sampler;
@vertex fn vertexMain(@builtin(vertex_index) index: u32) -> VertexOutput { let points = array<vec2f, 6>(vec2f(-1.0, -1.0), vec2f(1.0, -1.0), vec2f(-1.0, 1.0), vec2f(-1.0, 1.0), vec2f(1.0, -1.0), vec2f(1.0, 1.0)); let uv = array<vec2f, 6>(vec2f(0.0, 1.0), vec2f(1.0, 1.0), vec2f(0.0, 0.0), vec2f(0.0, 0.0), vec2f(1.0, 1.0), vec2f(1.0, 0.0)); var output: VertexOutput; output.position = vec4f(points[index], 0.0, 1.0); output.uv = uv[index]; return output; }
@fragment fn fragmentMain(input: VertexOutput) -> @location(0) vec4f { return textureSample(sourceTexture, sourceSampler, input.uv); }`;

function browserWebGpuProbe(): WebGpuProbe | undefined { return (globalThis.navigator as Navigator & { gpu?: WebGpuProbe }).gpu; }
export function createViewport(width: number, height: number, devicePixelRatio = 1, zoom = 1, offsetX = 0, offsetY = 0): RenderViewport { if (![width, height, devicePixelRatio, zoom, offsetX, offsetY].every(Number.isFinite) || width <= 0 || height <= 0 || devicePixelRatio <= 0 || zoom <= 0) throw new RangeError("Viewport dimensions, pixel ratio, and zoom must be positive finite values"); return { width, height, devicePixelRatio, zoom, offsetX, offsetY }; }
export function calculatePhysicalSurfaceSize(viewport: RenderViewport): { width: number; height: number } { return physicalSurfaceSize(viewport); }

class RendererRuntime implements Renderer {
  #surface?: HTMLCanvasElement; #backend?: RenderBackend; #viewport = createViewport(1, 1); #status: RendererStatus = "idle"; #detail: RendererStatusDetail = { status: "idle" }; #input?: RenderInput; #plan?: RenderPlan; #options?: RenderOptions; #preview?: RenderLayerTransformPreview; #refreshResources = false; #frame?: number; #unsubscribeRaster?: () => void; #generation = 0; #initialization?: { generation: number; promise: Promise<void> };
  constructor(private readonly dependencies: RendererDependencies) { this.#unsubscribeRaster = dependencies.rasterSources?.subscribe?.(sourceId => { this.#backend?.invalidateRaster(sourceId); this.invalidate(); }); }
  get status(): RendererStatus { return this.#status; } get detail(): RendererStatusDetail { return this.#detail; } get viewport(): RenderViewport { return this.#viewport; }
  attach(surface: HTMLCanvasElement): void { if (this.#status === "disposed") throw new Error("Renderer is disposed"); if (this.#surface && this.#surface !== surface) { this.#generation += 1; this.#cancelFrame(); this.#backend?.dispose(); this.#backend = undefined; this.#set("idle"); } this.#surface = surface; this.#applySize(); }
  initialize(): Promise<void> { if (this.#status === "disposed") return Promise.reject(new Error("Renderer is disposed")); if (this.#status === "ready" || this.#status === "fallback") return Promise.resolve(); if (!this.#surface) { this.#fail("unavailable", "surface-unavailable", "A canvas surface must be attached before initialization"); return Promise.resolve(); } const generation = this.#generation; if (this.#initialization?.generation === generation) return this.#initialization.promise; const promise = this.#initializeBackend(generation).finally(() => { if (this.#initialization?.promise === promise) this.#initialization = undefined; }); this.#initialization = { generation, promise }; return promise; }
  resize(viewport: RenderViewport): void { if (this.#status === "disposed") return; this.#viewport = viewport; this.#applySize(); this.#backend?.resize(viewport); this.invalidate(); }
  setZoom(zoom: number): void { this.#updateViewport(withZoom(this.#viewport, zoom)); } zoomBy(factor: number, point = { x: this.#viewport.width / 2, y: this.#viewport.height / 2 }): void { if (!Number.isFinite(factor) || factor <= 0) throw new RangeError("Zoom factor must be positive and finite"); this.zoomAt(point, this.#viewport.zoom * factor); } zoomAt(point: { x: number; y: number }, zoom: number): void { this.#updateViewport(zoomAround(this.#viewport, point, clampZoom(zoom))); } setPan(offset: { x: number; y: number }): void { this.#updateViewport(panTo(this.#viewport, offset)); } panBy(delta: { x: number; y: number }): void { this.#updateViewport(panBy(this.#viewport, delta)); } fitDocument(input: RenderInput, padding?: number): void { this.#updateViewport(fitDocument(inputSize(input), this.#viewport, padding)); } fitWidth(input: RenderInput, padding?: number): void { this.#updateViewport(fitWidth(inputSize(input), this.#viewport, padding)); } actualSize(input: RenderInput): void { this.#updateViewport(actualSize(inputSize(input), this.#viewport)); }
  async render(input?: RenderInput, options?: RenderOptions): Promise<void> { if (this.#status === "disposed") throw new Error("Renderer is disposed"); this.#input = input; this.#plan = input ? createRenderPlan(input) : undefined; this.#options = options; this.#refreshResources = true; this.invalidate(); }
  /** Updates only renderer-owned transient metadata; it reuses the current immutable RenderInput and plan. */
  setLayerTransformPreview(preview?: RenderLayerTransformPreview): void { if (this.#status === "disposed") return; if (preview && (![preview.documentDelta.x, preview.documentDelta.y].every(Number.isFinite) || !preview.layerId)) throw new RangeError("Preview layer ID and document delta must be finite"); this.#preview = preview; this.invalidate(); }
  invalidate(): void { if (!this.#backend || this.#frame !== undefined || this.#status === "disposed") return; this.#frame = (this.dependencies.scheduler ?? defaultScheduler).request(() => { this.#frame = undefined; const backend = this.#backend; const refreshResources = this.#refreshResources; this.#refreshResources = false; try { backend?.render(this.#input, this.#plan, this.#viewport, this.#options, refreshResources, this.#preview); if (backend && backend === this.#backend) this.#detail = { ...this.#detail, issues: [...backend.issues] }; } catch (cause) { this.#fail("unavailable", "render-failed", "Renderer failed to draw a frame", cause); } }); }
  dispose(): void { if (this.#status === "disposed") return; this.#generation += 1; this.#cancelFrame(); this.#unsubscribeRaster?.(); this.#unsubscribeRaster = undefined; this.#backend?.dispose(); this.#backend = undefined; this.#surface = undefined; this.#input = undefined; this.#plan = undefined; this.#preview = undefined; this.#set("disposed"); }
  async #initializeBackend(generation: number): Promise<void> { if (!this.#surface || generation !== this.#generation) return; this.#set("initializing"); const surface = this.#surface; const resolver = this.dependencies.rasterSources ?? noRasterSources; const sampling = this.dependencies.sampling ?? "linear"; const probe = this.dependencies.webGpu ?? browserWebGpuProbe(); if (probe) { const backend = new WebGpuBackend(probe, resolver, sampling); try { await backend.initialize(surface, this.#viewport); if (generation !== this.#generation || this.#status === "disposed") { backend.dispose(); return; } this.#backend = backend; this.#set("ready", "webgpu"); return; } catch (cause) { backend.dispose(); if (generation !== this.#generation || this.#status === "disposed") return; this.#detail = { status: "initializing", error: { code: "webgpu-initialization-failed", message: "WebGPU initialization failed; attempting Canvas 2D fallback", cause } }; } } else this.#detail = { status: "initializing", error: { code: "webgpu-unavailable", message: "WebGPU is unavailable; attempting Canvas 2D fallback" } }; const backend = new Canvas2dBackend(resolver, this.dependencies.canvasRasterFactory ?? defaultCanvasRasterFactory, this.dependencies.canvasCompositeSurfaceFactory ?? defaultCanvasCompositeSurfaceFactory, sampling); try { await backend.initialize(surface, this.#viewport); if (generation !== this.#generation || this.#status === "disposed") { backend.dispose(); return; } this.#backend = backend; this.#set("fallback", "canvas2d", this.#detail.error); } catch (cause) { backend.dispose(); if (generation === this.#generation && this.#status !== "disposed") this.#fail("unavailable", "fallback-unavailable", "No render backend is available", cause); } }
  #updateViewport(viewport: RenderViewport): void { if (this.#status === "disposed") return; const oldSize = physicalSurfaceSize(this.#viewport); this.#viewport = viewport; const newSize = physicalSurfaceSize(viewport); if (oldSize.width !== newSize.width || oldSize.height !== newSize.height) { this.#applySize(); this.#backend?.resize(viewport); } this.invalidate(); }
  #cancelFrame(): void { if (this.#frame !== undefined) (this.dependencies.scheduler ?? defaultScheduler).cancel(this.#frame); this.#frame = undefined; }
  #applySize(): void { if (!this.#surface) return; const size = physicalSurfaceSize(this.#viewport); this.#surface.width = size.width; this.#surface.height = size.height; this.#surface.style.width = `${this.#viewport.width}px`; this.#surface.style.height = `${this.#viewport.height}px`; }
  #set(status: RendererStatus, backend?: RenderBackendKind, error?: RendererError): void { this.#status = status; this.#detail = { status, backend, error }; } #fail(status: RendererStatus, code: RendererError["code"], message: string, cause?: unknown): void { this.#backend?.dispose(); this.#backend = undefined; this.#set(status, undefined, { code, message, cause }); }
}
/** Creates an invalidation-driven renderer; backend selection remains internal. */
export function createRenderer(dependencies: RendererDependencies = {}): Renderer { return new RendererRuntime(dependencies); }
