import type { RenderBackendKind, RenderInput, RenderOptions, Renderer, RendererError, RendererStatus, RendererStatusDetail, RenderViewport } from "./contracts";
import { createRenderPlan } from "./render-plan";
import { InMemoryRasterSourceResolver, RasterResourceCache, type RasterSource, type RasterSourceResolver, sourceColor } from "./raster-source";
import { multiplyAffine, type AffineTransform } from "./transform";
import { actualSize, clampZoom, documentBounds, fitDocument, fitWidth, inputSize, panBy, panTo, physicalSurfaceSize, withZoom, zoomAround } from "./viewport";

export interface WebGpuDevice { readonly queue?: { submit(commands: unknown[]): void; writeBuffer?(buffer: unknown, offset: number, data: ArrayBufferView): void }; createCommandEncoder?(): WebGpuCommandEncoder; createShaderModule?(descriptor: { code: string }): unknown; createBindGroupLayout?(descriptor: unknown): unknown; createPipelineLayout?(descriptor: unknown): unknown; createRenderPipeline?(descriptor: unknown): unknown; createBuffer?(descriptor: unknown): unknown; createBindGroup?(descriptor: unknown): unknown; }
export interface WebGpuAdapter { readonly name?: string; requestDevice?(): Promise<WebGpuDevice>; }
export interface WebGpuProbe { requestAdapter(): Promise<WebGpuAdapter | null>; getPreferredCanvasFormat?(): string; }
export interface WebGpuCommandEncoder { beginRenderPass(descriptor: unknown): { setPipeline(pipeline: unknown): void; setBindGroup(index: number, group: unknown): void; draw(vertices: number): void; end(): void }; finish(): unknown; }
export interface FrameScheduler { request(callback: () => void): number; cancel(handle: number): void; }
export interface RendererDependencies { readonly webGpu?: WebGpuProbe; readonly scheduler?: FrameScheduler; readonly rasterSources?: RasterSourceResolver; }
interface RenderBackend { readonly kind: RenderBackendKind; initialize(surface: HTMLCanvasElement, viewport: RenderViewport): Promise<void>; resize(viewport: RenderViewport): void; render(input: RenderInput | undefined, viewport: RenderViewport, options: RenderOptions | undefined): void; dispose(): void; }
interface WebGpuCanvasContext { configure(config: { device: WebGpuDevice; format: string; alphaMode: "opaque" }): void; getCurrentTexture(): { createView(): unknown }; }

const defaultScheduler: FrameScheduler = { request: callback => typeof requestAnimationFrame === "function" ? requestAnimationFrame(callback) : setTimeout(callback, 0) as unknown as number, cancel: handle => typeof cancelAnimationFrame === "function" ? cancelAnimationFrame(handle) : clearTimeout(handle) };
const noRasterSources = new InMemoryRasterSourceResolver();
function viewportAffine(viewport: RenderViewport): AffineTransform { return { a: viewport.zoom * viewport.devicePixelRatio, b: 0, c: 0, d: viewport.zoom * viewport.devicePixelRatio, e: viewport.offsetX * viewport.devicePixelRatio, f: viewport.offsetY * viewport.devicePixelRatio }; }
function colorStyle(source: RasterSource): string { const [r, g, b, a] = source.color; return `rgba(${r}, ${g}, ${b}, ${a / 255})`; }

class Canvas2dBackend implements RenderBackend {
  readonly kind = "canvas2d" as const;
  #context?: CanvasRenderingContext2D; #resources: RasterResourceCache<RasterSource>;
  constructor(resolver: RasterSourceResolver) { this.#resources = new RasterResourceCache(resolver, source => source); }
  async initialize(surface: HTMLCanvasElement, _viewport: RenderViewport): Promise<void> { const context = surface.getContext("2d"); if (!context) throw new Error("Canvas 2D context is unavailable"); this.#context = context; }
  resize(_viewport: RenderViewport): void {}
  render(input: RenderInput | undefined, viewport: RenderViewport, _options: RenderOptions | undefined): void {
    if (!this.#context) throw new Error("Canvas backend is not initialized"); const context = this.#context;
    context.save(); context.setTransform(viewport.devicePixelRatio, 0, 0, viewport.devicePixelRatio, 0, 0); context.globalAlpha = 1; context.fillStyle = "#1b1f2a"; context.fillRect(0, 0, viewport.width, viewport.height);
    if (input) {
      const board = documentBounds(inputSize(input), viewport); context.beginPath(); context.rect(0, 0, viewport.width, viewport.height); context.clip(); context.fillStyle = "#f2f3f5"; context.fillRect(board.x, board.y, board.width, board.height); context.strokeStyle = "#9aa0a8"; context.lineWidth = 1 / viewport.devicePixelRatio; context.strokeRect(board.x, board.y, board.width, board.height);
      const view = viewportAffine(viewport); for (const layer of createRenderPlan(input).layers) { const source = this.#resources.get(layer.raster); if (!source) continue; const transform = multiplyAffine(view, layer.transform); context.save(); context.setTransform(transform.a, transform.b, transform.c, transform.d, transform.e, transform.f); context.globalAlpha = layer.opacity; context.fillStyle = colorStyle(source); context.fillRect(0, 0, source.width, source.height); context.restore(); }
    }
    context.restore();
  }
  dispose(): void { this.#context = undefined; this.#resources.dispose(); }
}
class WebGpuBackend implements RenderBackend {
  readonly kind = "webgpu" as const; #device?: WebGpuDevice; #context?: WebGpuCanvasContext; #format?: string; #pipeline?: unknown; #layout?: unknown; #uniforms: unknown[] = []; #resources: RasterResourceCache<RasterSource>;
  constructor(private readonly probe: WebGpuProbe, resolver: RasterSourceResolver) { this.#resources = new RasterResourceCache(resolver, source => source); }
  async initialize(surface: HTMLCanvasElement, _viewport: RenderViewport): Promise<void> {
    const adapter = await this.probe.requestAdapter(); if (!adapter?.requestDevice) throw new Error("WebGPU adapter or device is unavailable"); const context = surface.getContext("webgpu") as unknown as WebGpuCanvasContext | null; if (!context) throw new Error("WebGPU canvas context is unavailable"); this.#device = await adapter.requestDevice(); this.#context = context; this.#format = this.probe.getPreferredCanvasFormat?.() ?? "bgra8unorm";
    const device = this.#device; if (!device.createShaderModule || !device.createBindGroupLayout || !device.createPipelineLayout || !device.createRenderPipeline || !device.createBuffer || !device.createBindGroup) throw new Error("WebGPU quad resources are unavailable");
    const module = device.createShaderModule({ code: QUAD_SHADER }); const layout = device.createBindGroupLayout({ entries: [{ binding: 0, visibility: 3, buffer: { type: "uniform" } }] }); this.#layout = layout; this.#pipeline = device.createRenderPipeline({ layout: device.createPipelineLayout({ bindGroupLayouts: [layout] }), vertex: { module, entryPoint: "vertexMain" }, fragment: { module, entryPoint: "fragmentMain", targets: [{ format: this.#format, blend: { color: { srcFactor: "src-alpha", dstFactor: "one-minus-src-alpha" }, alpha: { srcFactor: "one", dstFactor: "one-minus-src-alpha" } } }] }, primitive: { topology: "triangle-list" } }); context.configure({ device, format: this.#format, alphaMode: "opaque" });
  }
  resize(_viewport: RenderViewport): void { if (this.#context && this.#device && this.#format) this.#context.configure({ device: this.#device, format: this.#format, alphaMode: "opaque" }); }
  render(input: RenderInput | undefined, viewport: RenderViewport, _options: RenderOptions | undefined): void {
    if (!this.#device?.createCommandEncoder || !this.#device.queue || !this.#context || !this.#pipeline || !this.#layout) throw new Error("WebGPU backend is not initialized"); const encoder = this.#device.createCommandEncoder(); const pass = encoder.beginRenderPass({ colorAttachments: [{ view: this.#context.getCurrentTexture().createView(), clearValue: { r: 0.106, g: 0.122, b: 0.165, a: 1 }, loadOp: "clear", storeOp: "store" }] });
    if (input) { const view = viewportAffine(viewport); const physical = physicalSurfaceSize(viewport); const quads = [{ transform: view, width: input.width, height: input.height, color: { r: 0.949, g: 0.953, b: 0.961, a: 1 } }, ...createRenderPlan(input).layers.flatMap(layer => { const source = this.#resources.get(layer.raster); if (!source) return []; const color = sourceColor(source); return [{ transform: multiplyAffine(view, layer.transform), width: source.width, height: source.height, color: { ...color, a: color.a * layer.opacity } }]; })]; this.#ensureUniforms(quads.length); quads.forEach((quad, index) => this.#drawQuad(pass, this.#uniforms[index], quad.transform, quad.width, quad.height, quad.color, physical)); }
    pass.end(); this.#device.queue.submit([encoder.finish()]);
  }
  #ensureUniforms(count: number): void { while (this.#uniforms.length < count) { const uniform = this.#device!.createBuffer!({ size: 64, usage: 72 }); const group = this.#device!.createBindGroup!({ layout: this.#layout, entries: [{ binding: 0, resource: { buffer: uniform } }] }); this.#uniforms.push({ uniform, group }); } }
  #drawQuad(pass: { setPipeline(pipeline: unknown): void; setBindGroup(index: number, group: unknown): void; draw(vertices: number): void }, resource: unknown, transform: AffineTransform, width: number, height: number, color: { r: number; g: number; b: number; a: number }, physical: { width: number; height: number }): void { const pair = resource as { uniform: unknown; group: unknown }; this.#device!.queue!.writeBuffer?.(pair.uniform, 0, new Float32Array([transform.a, transform.b, transform.c, transform.d, transform.e, transform.f, width, height, color.r, color.g, color.b, color.a, physical.width, physical.height, 0, 0])); pass.setPipeline(this.#pipeline!); pass.setBindGroup(0, pair.group); pass.draw(6); }
  dispose(): void { this.#context = undefined; this.#device = undefined; this.#format = undefined; this.#pipeline = undefined; this.#layout = undefined; this.#uniforms = []; this.#resources.dispose(); }
}
const QUAD_SHADER = `struct Quad { linear: vec4f, translation: vec4f, color: vec4f, surface: vec4f }
@group(0) @binding(0) var<uniform> quad: Quad;
@vertex fn vertexMain(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  let points = array<vec2f, 6>(vec2f(0.0, 0.0), vec2f(1.0, 0.0), vec2f(0.0, 1.0), vec2f(0.0, 1.0), vec2f(1.0, 0.0), vec2f(1.0, 1.0)); let source = points[index] * quad.translation.zw;
  let point = vec2f(quad.linear.x * source.x + quad.linear.z * source.y + quad.translation.x, quad.linear.y * source.x + quad.linear.w * source.y + quad.translation.y);
  return vec4f(point.x / quad.surface.x * 2.0 - 1.0, 1.0 - point.y / quad.surface.y * 2.0, 0.0, 1.0);
}
@fragment fn fragmentMain() -> @location(0) vec4f { return quad.color; }`;
function browserWebGpuProbe(): WebGpuProbe | undefined { return (globalThis.navigator as Navigator & { gpu?: WebGpuProbe }).gpu; }
export function createViewport(width: number, height: number, devicePixelRatio = 1, zoom = 1, offsetX = 0, offsetY = 0): RenderViewport { if (![width, height, devicePixelRatio, zoom, offsetX, offsetY].every(Number.isFinite) || width <= 0 || height <= 0 || devicePixelRatio <= 0 || zoom <= 0) throw new RangeError("Viewport dimensions, pixel ratio, and zoom must be positive finite values"); return { width, height, devicePixelRatio, zoom, offsetX, offsetY }; }
export function calculatePhysicalSurfaceSize(viewport: RenderViewport): { width: number; height: number } { return physicalSurfaceSize(viewport); }

class RendererRuntime implements Renderer {
  #surface?: HTMLCanvasElement; #backend?: RenderBackend; #viewport = createViewport(1, 1); #status: RendererStatus = "idle"; #detail: RendererStatusDetail = { status: "idle" }; #input?: RenderInput; #options?: RenderOptions; #frame?: number;
  constructor(private readonly dependencies: RendererDependencies) {}
  get status(): RendererStatus { return this.#status; } get detail(): RendererStatusDetail { return this.#detail; } get viewport(): RenderViewport { return this.#viewport; }
  attach(surface: HTMLCanvasElement): void { if (this.#status === "disposed") throw new Error("Renderer is disposed"); if (this.#surface && this.#surface !== surface) { this.#backend?.dispose(); this.#backend = undefined; this.#set("idle"); } this.#surface = surface; this.#applySize(); }
  async initialize(): Promise<void> { if (this.#status === "disposed") throw new Error("Renderer is disposed"); if (!this.#surface) return this.#fail("unavailable", "surface-unavailable", "A canvas surface must be attached before initialization"); this.#set("initializing"); const resolver = this.dependencies.rasterSources ?? noRasterSources; const probe = this.dependencies.webGpu ?? browserWebGpuProbe(); if (probe) { try { const backend = new WebGpuBackend(probe, resolver); await backend.initialize(this.#surface, this.#viewport); this.#backend = backend; this.#set("ready", "webgpu"); return; } catch (cause) { this.#detail = { status: "initializing", error: { code: "webgpu-initialization-failed", message: "WebGPU initialization failed; attempting Canvas 2D fallback", cause } }; } } else this.#detail = { status: "initializing", error: { code: "webgpu-unavailable", message: "WebGPU is unavailable; attempting Canvas 2D fallback" } }; try { const backend = new Canvas2dBackend(resolver); await backend.initialize(this.#surface, this.#viewport); this.#backend = backend; this.#set("fallback", "canvas2d", this.#detail.error); } catch (cause) { this.#fail("unavailable", "fallback-unavailable", "No render backend is available", cause); } }
  resize(viewport: RenderViewport): void { if (this.#status === "disposed") return; this.#viewport = viewport; this.#applySize(); this.#backend?.resize(viewport); this.invalidate(); }
  setZoom(zoom: number): void { this.#updateViewport(withZoom(this.#viewport, zoom)); } zoomBy(factor: number, point = { x: this.#viewport.width / 2, y: this.#viewport.height / 2 }): void { if (!Number.isFinite(factor) || factor <= 0) throw new RangeError("Zoom factor must be positive and finite"); this.zoomAt(point, this.#viewport.zoom * factor); } zoomAt(point: { x: number; y: number }, zoom: number): void { this.#updateViewport(zoomAround(this.#viewport, point, clampZoom(zoom))); } setPan(offset: { x: number; y: number }): void { this.#updateViewport(panTo(this.#viewport, offset)); } panBy(delta: { x: number; y: number }): void { this.#updateViewport(panBy(this.#viewport, delta)); } fitDocument(input: RenderInput, padding?: number): void { this.#updateViewport(fitDocument(inputSize(input), this.#viewport, padding)); } fitWidth(input: RenderInput, padding?: number): void { this.#updateViewport(fitWidth(inputSize(input), this.#viewport, padding)); } actualSize(input: RenderInput): void { this.#updateViewport(actualSize(inputSize(input), this.#viewport)); }
  async render(input?: RenderInput, options?: RenderOptions): Promise<void> { if (this.#status === "disposed") throw new Error("Renderer is disposed"); this.#input = input; this.#options = options; this.invalidate(); }
  invalidate(): void { if (!this.#backend || this.#frame !== undefined || this.#status === "disposed") return; this.#frame = (this.dependencies.scheduler ?? defaultScheduler).request(() => { this.#frame = undefined; try { this.#backend?.render(this.#input, this.#viewport, this.#options); } catch (cause) { this.#fail("unavailable", "render-failed", "Renderer failed to draw a frame", cause); } }); }
  dispose(): void { if (this.#status === "disposed") return; if (this.#frame !== undefined) (this.dependencies.scheduler ?? defaultScheduler).cancel(this.#frame); this.#frame = undefined; this.#backend?.dispose(); this.#backend = undefined; this.#surface = undefined; this.#set("disposed"); }
  #updateViewport(viewport: RenderViewport): void { if (this.#status === "disposed") return; const oldSize = physicalSurfaceSize(this.#viewport); this.#viewport = viewport; const newSize = physicalSurfaceSize(viewport); if (oldSize.width !== newSize.width || oldSize.height !== newSize.height) { this.#applySize(); this.#backend?.resize(viewport); } this.invalidate(); }
  #applySize(): void { if (!this.#surface) return; const size = physicalSurfaceSize(this.#viewport); this.#surface.width = size.width; this.#surface.height = size.height; this.#surface.style.width = `${this.#viewport.width}px`; this.#surface.style.height = `${this.#viewport.height}px`; }
  #set(status: RendererStatus, backend?: RenderBackendKind, error?: RendererError): void { this.#status = status; this.#detail = { status, backend, error }; } #fail(status: RendererStatus, code: RendererError["code"], message: string, cause?: unknown): void { this.#backend?.dispose(); this.#backend = undefined; this.#set(status, undefined, { code, message, cause }); }
}
/** Creates an invalidation-driven renderer; backend selection remains internal. */
export function createRenderer(dependencies: RendererDependencies = {}): Renderer { return new RendererRuntime(dependencies); }
