import type { RenderBackendKind, RenderInput, RenderOptions, Renderer, RendererError, RendererStatus, RendererStatusDetail, RenderViewport } from "./contracts";
import { createRenderPlan } from "./render-plan";
import { createSolidRasterSource, InMemoryRasterSourceResolver, prepareTextureUpload, RasterResourceCache, type RasterSource, type RasterSourceResolver } from "./raster-source";
import { multiplyAffine, type AffineTransform } from "./transform";
import { actualSize, clampZoom, documentBounds, fitDocument, fitWidth, inputSize, panBy, panTo, physicalSurfaceSize, withZoom, zoomAround } from "./viewport";

export type TextureSampling = "nearest" | "linear";
export interface WebGpuTexture { createView(): unknown; destroy?(): void; }
export interface WebGpuDevice {
  readonly queue?: { submit(commands: unknown[]): void; writeBuffer?(buffer: unknown, offset: number, data: ArrayBufferView): void; writeTexture?(destination: { texture: WebGpuTexture }, data: ArrayBufferView, layout: { bytesPerRow: number; rowsPerImage: number }, size: { width: number; height: number; depthOrArrayLayers: number }): void };
  createCommandEncoder?(): WebGpuCommandEncoder; createShaderModule?(descriptor: { code: string }): unknown; createBindGroupLayout?(descriptor: unknown): unknown; createPipelineLayout?(descriptor: unknown): unknown; createRenderPipeline?(descriptor: unknown): unknown; createBuffer?(descriptor: unknown): unknown; createBindGroup?(descriptor: unknown): unknown; createTexture?(descriptor: unknown): WebGpuTexture; createSampler?(descriptor: unknown): unknown;
}
export interface WebGpuAdapter { readonly name?: string; requestDevice?(): Promise<WebGpuDevice>; }
export interface WebGpuProbe { requestAdapter(): Promise<WebGpuAdapter | null>; getPreferredCanvasFormat?(): string; }
export interface WebGpuCommandEncoder { beginRenderPass(descriptor: unknown): { setPipeline(pipeline: unknown): void; setBindGroup(index: number, group: unknown): void; draw(vertices: number): void; end(): void }; finish(): unknown; }
export interface FrameScheduler { request(callback: () => void): number; cancel(handle: number): void; }
export type CanvasRasterFactory = (source: RasterSource) => CanvasImageSource;
export interface RendererDependencies { readonly webGpu?: WebGpuProbe; readonly scheduler?: FrameScheduler; readonly rasterSources?: RasterSourceResolver; readonly sampling?: TextureSampling; readonly canvasRasterFactory?: CanvasRasterFactory; }
interface RenderBackend { readonly kind: RenderBackendKind; initialize(surface: HTMLCanvasElement, viewport: RenderViewport): Promise<void>; resize(viewport: RenderViewport): void; render(input: RenderInput | undefined, viewport: RenderViewport, options: RenderOptions | undefined): void; invalidateRaster(sourceId: string): void; dispose(): void; }
interface WebGpuCanvasContext { configure(config: { device: WebGpuDevice; format: string; alphaMode: "opaque" }): void; getCurrentTexture(): { createView(): unknown }; }
interface CanvasRasterResource { readonly width: number; readonly height: number; readonly drawable: CanvasImageSource; }
interface GpuTextureResource { readonly key: string; readonly width: number; readonly height: number; readonly texture: WebGpuTexture; readonly view: unknown; }
interface GpuDrawResource { readonly uniform: unknown; key?: string; group?: unknown; }

const defaultScheduler: FrameScheduler = { request: callback => typeof requestAnimationFrame === "function" ? requestAnimationFrame(callback) : setTimeout(callback, 0) as unknown as number, cancel: handle => typeof cancelAnimationFrame === "function" ? cancelAnimationFrame(handle) : clearTimeout(handle) };
const noRasterSources = new InMemoryRasterSourceResolver();
function viewportAffine(viewport: RenderViewport): AffineTransform { return { a: viewport.zoom * viewport.devicePixelRatio, b: 0, c: 0, d: viewport.zoom * viewport.devicePixelRatio, e: viewport.offsetX * viewport.devicePixelRatio, f: viewport.offsetY * viewport.devicePixelRatio }; }
function defaultCanvasRasterFactory(source: RasterSource): CanvasImageSource {
  const surface = typeof OffscreenCanvas === "function" ? new OffscreenCanvas(source.width, source.height) : document.createElement("canvas"); surface.width = source.width; surface.height = source.height;
  const context = surface.getContext("2d") as CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D | null; if (!context) throw new Error("Canvas raster resource context is unavailable"); const image = context.createImageData(source.width, source.height); image.data.set(source.pixels); context.putImageData(image, 0, 0); return surface as CanvasImageSource;
}

class Canvas2dBackend implements RenderBackend {
  readonly kind = "canvas2d" as const; #context?: CanvasRenderingContext2D; #resources: RasterResourceCache<CanvasRasterResource>;
  constructor(resolver: RasterSourceResolver, factory: CanvasRasterFactory, private readonly sampling: TextureSampling) { this.#resources = new RasterResourceCache(resolver, source => ({ width: source.width, height: source.height, drawable: factory(source) })); }
  async initialize(surface: HTMLCanvasElement, _viewport: RenderViewport): Promise<void> { const context = surface.getContext("2d"); if (!context) throw new Error("Canvas 2D context is unavailable"); this.#context = context; }
  resize(_viewport: RenderViewport): void {}
  render(input: RenderInput | undefined, viewport: RenderViewport, _options: RenderOptions | undefined): void {
    if (!this.#context) throw new Error("Canvas backend is not initialized"); const context = this.#context; context.save(); context.setTransform(viewport.devicePixelRatio, 0, 0, viewport.devicePixelRatio, 0, 0); context.globalAlpha = 1; context.fillStyle = "#1b1f2a"; context.fillRect(0, 0, viewport.width, viewport.height);
    if (input) { const board = documentBounds(inputSize(input), viewport); context.beginPath(); context.rect(0, 0, viewport.width, viewport.height); context.clip(); context.fillStyle = "#f2f3f5"; context.fillRect(board.x, board.y, board.width, board.height); context.strokeStyle = "#9aa0a8"; context.lineWidth = 1 / viewport.devicePixelRatio; context.strokeRect(board.x, board.y, board.width, board.height); context.imageSmoothingEnabled = this.sampling === "linear";
      const view = viewportAffine(viewport); for (const layer of createRenderPlan(input).layers) { const resource = this.#resources.get(layer.raster); if (!resource) continue; const transform = multiplyAffine(view, layer.transform); context.save(); context.setTransform(transform.a, transform.b, transform.c, transform.d, transform.e, transform.f); context.globalAlpha = layer.opacity; context.drawImage(resource.drawable, 0, 0, resource.width, resource.height); context.restore(); }
    }
    context.restore();
  }
  invalidateRaster(sourceId: string): void { this.#resources.invalidate(sourceId); }
  dispose(): void { this.#context = undefined; this.#resources.dispose(); }
}

class WebGpuBackend implements RenderBackend {
  readonly kind = "webgpu" as const; #device?: WebGpuDevice; #context?: WebGpuCanvasContext; #format?: string; #pipeline?: unknown; #layout?: unknown; #sampler?: unknown; #board?: GpuTextureResource; #drawResources: GpuDrawResource[] = []; #resources: RasterResourceCache<GpuTextureResource>;
  constructor(private readonly probe: WebGpuProbe, resolver: RasterSourceResolver, private readonly sampling: TextureSampling) { this.#resources = new RasterResourceCache(resolver, source => this.#uploadTexture(source), resource => resource.texture.destroy?.()); }
  async initialize(surface: HTMLCanvasElement, _viewport: RenderViewport): Promise<void> {
    const adapter = await this.probe.requestAdapter(); if (!adapter?.requestDevice) throw new Error("WebGPU adapter or device is unavailable"); const context = surface.getContext("webgpu") as unknown as WebGpuCanvasContext | null; if (!context) throw new Error("WebGPU canvas context is unavailable"); this.#device = await adapter.requestDevice(); this.#context = context; this.#format = this.probe.getPreferredCanvasFormat?.() ?? "bgra8unorm";
    const device = this.#device; if (!device.queue?.writeTexture || !device.createShaderModule || !device.createBindGroupLayout || !device.createPipelineLayout || !device.createRenderPipeline || !device.createBuffer || !device.createBindGroup || !device.createTexture || !device.createSampler) throw new Error("WebGPU texture resources are unavailable");
    const module = device.createShaderModule({ code: TEXTURE_SHADER }); const layout = device.createBindGroupLayout({ entries: [{ binding: 0, visibility: 3, buffer: { type: "uniform" } }, { binding: 1, visibility: 2, texture: { sampleType: "float", viewDimension: "2d" } }, { binding: 2, visibility: 2, sampler: { type: "filtering" } }] }); this.#layout = layout; this.#sampler = device.createSampler({ addressModeU: "clamp-to-edge", addressModeV: "clamp-to-edge", magFilter: this.sampling, minFilter: this.sampling }); this.#pipeline = device.createRenderPipeline({ layout: device.createPipelineLayout({ bindGroupLayouts: [layout] }), vertex: { module, entryPoint: "vertexMain" }, fragment: { module, entryPoint: "fragmentMain", targets: [{ format: this.#format, blend: { color: { srcFactor: "one", dstFactor: "one-minus-src-alpha" }, alpha: { srcFactor: "one", dstFactor: "one-minus-src-alpha" } } }] }, primitive: { topology: "triangle-list" } }); this.#board = this.#uploadTexture(createSolidRasterSource("renderer-board", 1, 1, [242, 243, 245, 255])); context.configure({ device, format: this.#format, alphaMode: "opaque" });
  }
  resize(_viewport: RenderViewport): void { if (this.#context && this.#device && this.#format) this.#context.configure({ device: this.#device, format: this.#format, alphaMode: "opaque" }); }
  render(input: RenderInput | undefined, viewport: RenderViewport, _options: RenderOptions | undefined): void {
    if (!this.#device?.createCommandEncoder || !this.#device.queue || !this.#context || !this.#pipeline || !this.#layout || !this.#sampler || !this.#board) throw new Error("WebGPU backend is not initialized"); const encoder = this.#device.createCommandEncoder(); const pass = encoder.beginRenderPass({ colorAttachments: [{ view: this.#context.getCurrentTexture().createView(), clearValue: { r: 0.106, g: 0.122, b: 0.165, a: 1 }, loadOp: "clear", storeOp: "store" }] });
    if (input) { const view = viewportAffine(viewport); const physical = physicalSurfaceSize(viewport); const draws: { resource: GpuTextureResource; transform: AffineTransform; width: number; height: number; opacity: number }[] = [{ resource: this.#board, transform: view, width: input.width, height: input.height, opacity: 1 }]; for (const layer of createRenderPlan(input).layers) { const resource = this.#resources.get(layer.raster); if (resource) draws.push({ resource, transform: multiplyAffine(view, layer.transform), width: resource.width, height: resource.height, opacity: layer.opacity }); } this.#ensureDrawResources(draws.length); draws.forEach((draw, index) => this.#drawQuad(pass, index, draw.resource, draw.transform, draw.width, draw.height, draw.opacity, physical)); }
    pass.end(); this.#device.queue.submit([encoder.finish()]);
  }
  #uploadTexture(source: RasterSource): GpuTextureResource { const upload = prepareTextureUpload(source); const texture = this.#device!.createTexture!({ size: { width: source.width, height: source.height, depthOrArrayLayers: 1 }, format: "rgba8unorm", usage: 6 }); this.#device!.queue!.writeTexture!({ texture }, upload.data, { bytesPerRow: upload.layout.bytesPerRow, rowsPerImage: upload.layout.rowsPerImage }, { width: source.width, height: source.height, depthOrArrayLayers: 1 }); return { key: `${source.id}:${source.revision}`, width: source.width, height: source.height, texture, view: texture.createView() }; }
  #ensureDrawResources(count: number): void { while (this.#drawResources.length < count) this.#drawResources.push({ uniform: this.#device!.createBuffer!({ size: 64, usage: 72 }) }); }
  #drawQuad(pass: { setPipeline(pipeline: unknown): void; setBindGroup(index: number, group: unknown): void; draw(vertices: number): void }, index: number, texture: GpuTextureResource, transform: AffineTransform, width: number, height: number, opacity: number, physical: { width: number; height: number }): void { const draw = this.#drawResources[index]; if (draw.key !== texture.key || !draw.group) { draw.key = texture.key; draw.group = this.#device!.createBindGroup!({ layout: this.#layout, entries: [{ binding: 0, resource: { buffer: draw.uniform } }, { binding: 1, resource: texture.view }, { binding: 2, resource: this.#sampler }] }); } this.#device!.queue!.writeBuffer?.(draw.uniform, 0, new Float32Array([transform.a, transform.b, transform.c, transform.d, transform.e, transform.f, width, height, opacity, 0, 0, 0, physical.width, physical.height, 0, 0])); pass.setPipeline(this.#pipeline!); pass.setBindGroup(0, draw.group); pass.draw(6); }
  invalidateRaster(sourceId: string): void { this.#resources.invalidate(sourceId); this.#drawResources.forEach(draw => { if (draw.key?.startsWith(`${sourceId}:`)) { draw.key = undefined; draw.group = undefined; } }); }
  dispose(): void { this.#resources.dispose(); this.#board?.texture.destroy?.(); this.#board = undefined; this.#context = undefined; this.#device = undefined; this.#format = undefined; this.#pipeline = undefined; this.#layout = undefined; this.#sampler = undefined; this.#drawResources = []; }
}

const TEXTURE_SHADER = `struct Quad { linear: vec4f, translation: vec4f, opacity: vec4f, surface: vec4f }
struct VertexOutput { @builtin(position) position: vec4f, @location(0) uv: vec2f }
@group(0) @binding(0) var<uniform> quad: Quad;
@group(0) @binding(1) var rasterTexture: texture_2d<f32>;
@group(0) @binding(2) var rasterSampler: sampler;
@vertex fn vertexMain(@builtin(vertex_index) index: u32) -> VertexOutput {
  let points = array<vec2f, 6>(vec2f(0.0, 0.0), vec2f(1.0, 0.0), vec2f(0.0, 1.0), vec2f(0.0, 1.0), vec2f(1.0, 0.0), vec2f(1.0, 1.0)); let uv = points[index]; let source = uv * quad.translation.zw; let point = vec2f(quad.linear.x * source.x + quad.linear.z * source.y + quad.translation.x, quad.linear.y * source.x + quad.linear.w * source.y + quad.translation.y); var output: VertexOutput; output.position = vec4f(point.x / quad.surface.x * 2.0 - 1.0, 1.0 - point.y / quad.surface.y * 2.0, 0.0, 1.0); output.uv = uv; return output;
}
@fragment fn fragmentMain(input: VertexOutput) -> @location(0) vec4f { let sampled = textureSample(rasterTexture, rasterSampler, input.uv); return sampled * quad.opacity.x; }`;
function browserWebGpuProbe(): WebGpuProbe | undefined { return (globalThis.navigator as Navigator & { gpu?: WebGpuProbe }).gpu; }
export function createViewport(width: number, height: number, devicePixelRatio = 1, zoom = 1, offsetX = 0, offsetY = 0): RenderViewport { if (![width, height, devicePixelRatio, zoom, offsetX, offsetY].every(Number.isFinite) || width <= 0 || height <= 0 || devicePixelRatio <= 0 || zoom <= 0) throw new RangeError("Viewport dimensions, pixel ratio, and zoom must be positive finite values"); return { width, height, devicePixelRatio, zoom, offsetX, offsetY }; }
export function calculatePhysicalSurfaceSize(viewport: RenderViewport): { width: number; height: number } { return physicalSurfaceSize(viewport); }

class RendererRuntime implements Renderer {
  #surface?: HTMLCanvasElement; #backend?: RenderBackend; #viewport = createViewport(1, 1); #status: RendererStatus = "idle"; #detail: RendererStatusDetail = { status: "idle" }; #input?: RenderInput; #options?: RenderOptions; #frame?: number; #unsubscribeRaster?: () => void;
  constructor(private readonly dependencies: RendererDependencies) { this.#unsubscribeRaster = dependencies.rasterSources?.subscribe?.(sourceId => { this.#backend?.invalidateRaster(sourceId); this.invalidate(); }); }
  get status(): RendererStatus { return this.#status; } get detail(): RendererStatusDetail { return this.#detail; } get viewport(): RenderViewport { return this.#viewport; }
  attach(surface: HTMLCanvasElement): void { if (this.#status === "disposed") throw new Error("Renderer is disposed"); if (this.#surface && this.#surface !== surface) { this.#backend?.dispose(); this.#backend = undefined; this.#set("idle"); } this.#surface = surface; this.#applySize(); }
  async initialize(): Promise<void> { if (this.#status === "disposed") throw new Error("Renderer is disposed"); if (!this.#surface) return this.#fail("unavailable", "surface-unavailable", "A canvas surface must be attached before initialization"); this.#set("initializing"); const resolver = this.dependencies.rasterSources ?? noRasterSources; const sampling = this.dependencies.sampling ?? "linear"; const probe = this.dependencies.webGpu ?? browserWebGpuProbe(); if (probe) { try { const backend = new WebGpuBackend(probe, resolver, sampling); await backend.initialize(this.#surface, this.#viewport); this.#backend = backend; this.#set("ready", "webgpu"); return; } catch (cause) { this.#detail = { status: "initializing", error: { code: "webgpu-initialization-failed", message: "WebGPU initialization failed; attempting Canvas 2D fallback", cause } }; } } else this.#detail = { status: "initializing", error: { code: "webgpu-unavailable", message: "WebGPU is unavailable; attempting Canvas 2D fallback" } }; try { const backend = new Canvas2dBackend(resolver, this.dependencies.canvasRasterFactory ?? defaultCanvasRasterFactory, sampling); await backend.initialize(this.#surface, this.#viewport); this.#backend = backend; this.#set("fallback", "canvas2d", this.#detail.error); } catch (cause) { this.#fail("unavailable", "fallback-unavailable", "No render backend is available", cause); } }
  resize(viewport: RenderViewport): void { if (this.#status === "disposed") return; this.#viewport = viewport; this.#applySize(); this.#backend?.resize(viewport); this.invalidate(); }
  setZoom(zoom: number): void { this.#updateViewport(withZoom(this.#viewport, zoom)); } zoomBy(factor: number, point = { x: this.#viewport.width / 2, y: this.#viewport.height / 2 }): void { if (!Number.isFinite(factor) || factor <= 0) throw new RangeError("Zoom factor must be positive and finite"); this.zoomAt(point, this.#viewport.zoom * factor); } zoomAt(point: { x: number; y: number }, zoom: number): void { this.#updateViewport(zoomAround(this.#viewport, point, clampZoom(zoom))); } setPan(offset: { x: number; y: number }): void { this.#updateViewport(panTo(this.#viewport, offset)); } panBy(delta: { x: number; y: number }): void { this.#updateViewport(panBy(this.#viewport, delta)); } fitDocument(input: RenderInput, padding?: number): void { this.#updateViewport(fitDocument(inputSize(input), this.#viewport, padding)); } fitWidth(input: RenderInput, padding?: number): void { this.#updateViewport(fitWidth(inputSize(input), this.#viewport, padding)); } actualSize(input: RenderInput): void { this.#updateViewport(actualSize(inputSize(input), this.#viewport)); }
  async render(input?: RenderInput, options?: RenderOptions): Promise<void> { if (this.#status === "disposed") throw new Error("Renderer is disposed"); this.#input = input; this.#options = options; this.invalidate(); }
  invalidate(): void { if (!this.#backend || this.#frame !== undefined || this.#status === "disposed") return; this.#frame = (this.dependencies.scheduler ?? defaultScheduler).request(() => { this.#frame = undefined; try { this.#backend?.render(this.#input, this.#viewport, this.#options); } catch (cause) { this.#fail("unavailable", "render-failed", "Renderer failed to draw a frame", cause); } }); }
  dispose(): void { if (this.#status === "disposed") return; if (this.#frame !== undefined) (this.dependencies.scheduler ?? defaultScheduler).cancel(this.#frame); this.#frame = undefined; this.#unsubscribeRaster?.(); this.#unsubscribeRaster = undefined; this.#backend?.dispose(); this.#backend = undefined; this.#surface = undefined; this.#set("disposed"); }
  #updateViewport(viewport: RenderViewport): void { if (this.#status === "disposed") return; const oldSize = physicalSurfaceSize(this.#viewport); this.#viewport = viewport; const newSize = physicalSurfaceSize(viewport); if (oldSize.width !== newSize.width || oldSize.height !== newSize.height) { this.#applySize(); this.#backend?.resize(viewport); } this.invalidate(); }
  #applySize(): void { if (!this.#surface) return; const size = physicalSurfaceSize(this.#viewport); this.#surface.width = size.width; this.#surface.height = size.height; this.#surface.style.width = `${this.#viewport.width}px`; this.#surface.style.height = `${this.#viewport.height}px`; }
  #set(status: RendererStatus, backend?: RenderBackendKind, error?: RendererError): void { this.#status = status; this.#detail = { status, backend, error }; } #fail(status: RendererStatus, code: RendererError["code"], message: string, cause?: unknown): void { this.#backend?.dispose(); this.#backend = undefined; this.#set(status, undefined, { code, message, cause }); }
}
/** Creates an invalidation-driven renderer; backend selection remains internal. */
export function createRenderer(dependencies: RendererDependencies = {}): Renderer { return new RendererRuntime(dependencies); }
